---

- name: celery restart
  service:
    state: restarted
    name: "{{ celery_app_name }}-{{ item.action|default('worker') }}{{ item.queue|default('') and ('-' + item.queue) or ''}}"
  with_items: "{{ celery_run }}"

- name: celery reload
  service:
    state: reloaded
    name: "{{ celery_app_name }}-{{ item.action|default('worker') }}{{ item.queue|default('') and ('-' + item.queue) or ''}}"
  with_items: "{{ celery_run }}"
